### ISSUE TITLE
Big Projects Upgrade

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/brain-game#64]
## Before
- [ ] Check if project could be archived
- [ ] Check and resolve any outstanding issues
- [ ] Check and resolve any outstanding pull requests
- [ ] Check branch and master are equal

## Projects site
- [ ] Check [projects site](https://learning-admin.raspberrypi.org) for feedback
- [ ] Check tags are correct (curriculum, hardware, software, interests and site-areas)

## Meta
- [ ] Increment version number
- [ ] Update last tested date
- [ ] Remove redundant meta tags (ingredient, duration, theme, curriculum, interest, site area, hardware, software, original_url)
- [ ] Remove step numbers from meta (and any step names)

## Directory structure and files
- [ ] `resources` directory containing all need assets (within `en`)
- [ ] `solutions` directory containing all needed solutions (within `en`)
- [ ] Add LICENSE.md if not exist
- [ ] Add a CONTRIBUTING.md if there isn’t one
- [ ] Update the README.md to link to the project, license and contributing
- [ ] Compile all solutions and resources directories into a resources.zip and solutions.zip as top level files

## On [Shortlinks](rpf.io/admin)
- [ ] Create rpf.io/project-name-go to link to the `resources.zip`
- [ ] Create rpf.io/project-name-get to link to the `solutions.zip`
- [ ] Create rpf.io/project-name-on to link to the online starter file if needed
- [ ] Create rpf.io/project-name-off to link to the offline starter file if needed

## Ingredients
- [ ] Update all ingredients used within a project, particularly with regard to new code syntax

## Step 1
- [ ] Add interactive showcase of project or GIF to step 1 within `--- no-print ---`
- [ ] Add image of project within `--- print-only ---`
- [ ] Add instructions for engaging with showcase before the showcase embed
- [ ] *What you will learn* inside a collapse (these are the learning objectives)
- [ ] *What you will need* inside a collapse
  - [ ] Contains a list of hardware
  - [ ] Contains a list of software
  - [ ] Contains a link to the rpf.io/project-name-go
- [ ] *Additional notes for educators* inside a collapse
  - [ ] Contains a link to the rpf.io/project-name-get
  - [ ] “If you need to print this project, please use the printer-friendly version.”

## Step 2
- [ ] Collapse content "Getting Started" if needed
  - [ ] Short link online resource and offline resource if needed.

## Tasks
- [ ] Where learner is asked to do something use the `--- task ---` syntax
- [ ] If the solution to a task requires some independence then add a hint within the task.

## Code
- [ ] Add image of sprite above the code block it is referring to if Scratch (64px in smallest dimension)
- [ ] Screenshots replaced with [markdown](https://docs.google.com/document/d/1w7s9TzCj3lVf-rh4umQlLyN8e_wbg9ptZizmQPvfwHw/edit#heading=h.6jpkqdmev6a4)
- [ ] If project is in Code Club book - check that the code matches

## Hints
- [ ] 1 per step max

## Ingredients
- [ ]  1 per step max

## Challenges
- [ ] Each Challenge has it's own step
- [ ] Must have challenge at end of project
- [ ] Challenge can be skipped and project still completed

## What next?
- [ ] Add a what next step at the end with links to other projects in the series or related projects.

## Fall-backs
- [ ] For all animated and embedded content include `--- no-print ---` and `--- print-only ---` sections

## Embeds
- [ ] Check Scratch and Trinket embeds use official account

## Translations
- [ ] Open issue for Nina citing that the project has been changed
